# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/nothing/camera

PRODUCT_COPY_FILES += \
    vendor/nothing/camera/proprietary/system/etc/permissions/NTCamera-google-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/NTCamera-google-permissions.xml \
    vendor/nothing/camera/proprietary/system/etc/permissions/NTCamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/NTCamera-permissions.xml \
    vendor/nothing/camera/proprietary/system/etc/permissions/privapp-permissions-platform-nothing.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-platform-nothing.xml

PRODUCT_PACKAGES += \
    NTCamera \
    NothingExperience
